#!/bin/sh
set -e

echo ">>> cargo fmt"
cargo fmt --all -- --check

echo ">>> cargo hakari generate"
cargo hakari generate --diff

echo ">>> cargo hakari manage-deps"
cargo hakari manage-deps --dry-run

echo ">>> cargo sqlx prepare"
cargo sqlx prepare --workspace

echo ">>> cargo clippy"
cargo clippy --all-targets --all-features -- -D warnings

echo ">>> cargo px build"
cargo px build

echo ">>> pre-commit passed"