//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: Router,
    application_state: ApplicationState,
}
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ApplicationConfig {
    #[serde(default)]
    pub cookies: biscotti::ProcessorConfig,
    pub database: app::configuration::DatabaseConfig,
    pub server: app::configuration::ServerConfig,
    #[serde(default)]
    pub session: pavex_session::SessionConfig,
}
pub struct ApplicationState {
    pub processor: biscotti::Processor,
    pub session_config: pavex_session::SessionConfig,
    pub session_store: pavex_session::SessionStore,
}
impl ApplicationState {
    pub async fn new(
        app_config: crate::ApplicationConfig,
    ) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
        Self::_new(&app_config.database, app_config.session, app_config.cookies).await
    }
    async fn _new(
        v0: &app::configuration::DatabaseConfig,
        v1: pavex_session::SessionConfig,
        v2: biscotti::ProcessorConfig,
    ) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
        let v3 = app::configuration::DatabaseConfig::get_pool(v0).await;
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = crate::ApplicationStateError::DatabaseConfigGetPool(v4);
                    core::result::Result::Err(v5)
                };
            }
        };
        let v5 = pavex_session_sqlx::PostgresSessionStore::new(v4);
        let v6 = <pavex_session::SessionStore as core::convert::From<
            pavex_session_sqlx::PostgresSessionStore,
        >>::from(v5);
        let v7 = pavex::cookie::config_into_processor(v2);
        let v8 = crate::ApplicationState {
            processor: v7,
            session_config: v1,
            session_store: v6,
        };
        core::result::Result::Ok(v8)
    }
}
#[derive(Debug, thiserror::Error)]
pub enum ApplicationStateError {
    #[error(transparent)]
    DatabaseConfigGetPool(sqlx_core::Error),
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    async fn handler(
        request: http::Request<hyper::body::Incoming>,
        connection_info: Option<pavex::connection::ConnectionInfo>,
        server_state: std::sync::Arc<ServerState>,
    ) -> pavex::Response {
        let (router, state) = (&server_state.router, &server_state.application_state);
        router.route(request, connection_info, state).await
    }
    let router = Router::new();
    let server_state = std::sync::Arc::new(ServerState {
        router,
        application_state,
    });
    server_builder.serve(handler, server_state)
}
struct Router {
    router: matchit::Router<u32>,
}
impl Router {
    /// Create a new router instance.
    ///
    /// This method is invoked once, when the server starts.
    pub fn new() -> Self {
        Self { router: Self::router() }
    }
    fn router() -> matchit::Router<u32> {
        let router = matchit::Router::new();
        router
    }
    pub async fn route(
        &self,
        request: http::Request<hyper::body::Incoming>,
        _connection_info: Option<pavex::connection::ConnectionInfo>,
        #[allow(unused)]
        state: &ApplicationState,
    ) -> pavex::Response {
        let (request_head, _) = request.into_parts();
        let request_head: pavex::request::RequestHead = request_head.into();
        let Ok(matched_route) = self.router.at(&request_head.target.path()) else {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "*",
            );
            return route_0::entrypoint(
                    matched_route_template,
                    &state.processor,
                    &request_head,
                    &state.session_config,
                    &state.session_store,
                    &allowed_methods,
                )
                .await;
        };
        match matched_route.value {
            i => unreachable!("Unknown route id: {}", i),
        }
    }
}
pub mod route_0 {
    pub async fn entrypoint<'a, 'b, 'c, 'd, 'e>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: &'a biscotti::Processor,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c pavex_session::SessionConfig,
        s_4: &'d pavex_session::SessionStore,
        s_5: &'e pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4, s_5).await;
        response
    }
    async fn stage_1<'a, 'b, 'c, 'd, 'e>(
        s_0: &'a biscotti::Processor,
        s_1: &'b pavex::request::RequestHead,
        s_2: &'c pavex_session::SessionConfig,
        s_3: &'d pavex_session::SessionStore,
        s_4: &'e pavex::router::AllowedMethods,
        s_5: pavex::request::path::MatchedPathPattern,
    ) -> pavex::Response {
        let response = wrapping_1(s_5, s_1, s_0, s_2, s_3, s_4).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd, 'e, 'f>(
        mut s_0: pavex::cookie::ResponseCookies,
        s_1: &'a biscotti::Processor,
        s_2: &'b pavex_tracing::RootSpan,
        s_3: &'c pavex::request::RequestHead,
        s_4: &'d pavex_session::SessionConfig,
        s_5: &'e pavex_session::SessionStore,
        s_6: &'f pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let response = handler(s_6).await;
        let response = post_processing_0(response, s_2).await;
        let response = post_processing_1(s_1, s_3, s_2, response, s_4, s_5, &mut s_0)
            .await;
        let response = post_processing_2(response, s_0, s_1, s_2).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &biscotti::Processor,
        v2: &pavex::request::RequestHead,
        v3: &pavex_session::SessionConfig,
        v4: &pavex_session::SessionStore,
        v5: &pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let v6 = crate::route_0::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v3,
            s_3: v4,
            s_4: v5,
            s_5: v0,
            next: stage_1,
        };
        let v7 = pavex::middleware::Next::new(v6);
        let v8 = pavex::middleware::wrap_noop(v7).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v8)
    }
    async fn wrapping_1(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &pavex::request::RequestHead,
        v2: &biscotti::Processor,
        v3: &pavex_session::SessionConfig,
        v4: &pavex_session::SessionStore,
        v5: &pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let v6 = pavex::telemetry::ServerRequestId::generate();
        let v7 = app::telemetry::root_span(v1, v0, v6);
        let v8 = pavex::cookie::ResponseCookies::new();
        let v9 = crate::route_0::Next1 {
            s_0: v8,
            s_1: v2,
            s_2: &v7,
            s_3: v1,
            s_4: v3,
            s_5: v4,
            s_6: v5,
            next: stage_2,
        };
        let v10 = pavex::middleware::Next::new(v9);
        let v11 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v7);
        let v12 = pavex_tracing::logger(v11, v10).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v12)
    }
    async fn handler(v0: &pavex::router::AllowedMethods) -> pavex::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v1)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    async fn post_processing_1(
        v0: &biscotti::Processor,
        v1: &pavex::request::RequestHead,
        v2: &pavex_tracing::RootSpan,
        v3: pavex::Response,
        v4: &pavex_session::SessionConfig,
        v5: &pavex_session::SessionStore,
        v6: &mut pavex::cookie::ResponseCookies,
    ) -> pavex::Response {
        let v7 = pavex::cookie::extract_request_cookies(v1, v0);
        let v8 = match v7 {
            Ok(ok) => ok,
            Err(v8) => {
                return {
                    let v9 = pavex::cookie::errors::ExtractRequestCookiesError::into_response(
                        &v8,
                    );
                    let v10 = pavex::Error::new(v8);
                    app::telemetry::error_logger(&v10, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v9)
                };
            }
        };
        let v9 = pavex_session::SessionConfig::cookie_config(v4);
        let v10 = pavex_session::IncomingSession::extract(&v8, v9);
        let v11 = pavex_session::Session::new(v5, v4, v10);
        let v12 = pavex_session::finalize_session(v3, v6, v0, v11).await;
        let v13 = match v12 {
            Ok(ok) => ok,
            Err(v13) => {
                return {
                    let v14 = pavex_session::errors::FinalizeError::into_response(&v13);
                    let v15 = pavex::Error::new(v13);
                    app::telemetry::error_logger(&v15, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v14)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v13)
    }
    async fn post_processing_2(
        v0: pavex::Response,
        v1: pavex::cookie::ResponseCookies,
        v2: &biscotti::Processor,
        v3: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v4 = pavex::cookie::inject_response_cookies(v0, v1, v2);
        let v5 = match v4 {
            Ok(ok) => ok,
            Err(v5) => {
                return {
                    let v6 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v5,
                    );
                    let v7 = pavex::Error::new(v5);
                    app::telemetry::error_logger(&v7, v3).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v6)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v5)
    }
    struct Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a biscotti::Processor,
        s_1: &'b pavex::request::RequestHead,
        s_2: &'c pavex_session::SessionConfig,
        s_3: &'d pavex_session::SessionStore,
        s_4: &'e pavex::router::AllowedMethods,
        s_5: pavex::request::path::MatchedPathPattern,
        next: fn(
            &'a biscotti::Processor,
            &'b pavex::request::RequestHead,
            &'c pavex_session::SessionConfig,
            &'d pavex_session::SessionStore,
            &'e pavex::router::AllowedMethods,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, T> std::future::IntoFuture for Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, 'e, 'f, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: pavex::cookie::ResponseCookies,
        s_1: &'a biscotti::Processor,
        s_2: &'b pavex_tracing::RootSpan,
        s_3: &'c pavex::request::RequestHead,
        s_4: &'d pavex_session::SessionConfig,
        s_5: &'e pavex_session::SessionStore,
        s_6: &'f pavex::router::AllowedMethods,
        next: fn(
            pavex::cookie::ResponseCookies,
            &'a biscotti::Processor,
            &'b pavex_tracing::RootSpan,
            &'c pavex::request::RequestHead,
            &'d pavex_session::SessionConfig,
            &'e pavex_session::SessionStore,
            &'f pavex::router::AllowedMethods,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, 'f, T> std::future::IntoFuture
    for Next1<'a, 'b, 'c, 'd, 'e, 'f, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self
                .next)(
                self.s_0,
                self.s_1,
                self.s_2,
                self.s_3,
                self.s_4,
                self.s_5,
                self.s_6,
            )
        }
    }
}
