[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "workspace"
yanked = "deny"
# Add a CVE to this list to "silence" it in CI
ignore = []