[package]
name = "app"
version = "0.1.0"
build = "build.rs"
edition.workspace = true

[[bin]]
path = "src/bin/bp.rs"
name = "bp"

[lints.rust]
# `pavex_ide_hint` is used in Pavex's `f!` macro to "nudge" the IDE
# and force it to provide completions and "go-to-definition" correctly
# for the paths passed to the `f!` macro.
# It must be allowed in all local crates that use `f!`.
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(pavex_ide_hint)'] }

[dependencies]
cargo_px_env = "0.1"
humantime-serde = "1.1"
pavex = { version = "0.2.10" }
pavex_tracing = { version = "0.2.10" }
pavex_cli_client = { version = "0.2.10" }
tracing = "0.1"
tracing_log_error = "0.1"
serde = { version = "1", features = ["derive"] }
serde-aux = "4"
workspace_hack = { version = "0.1", path = "../workspace_hack" }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "migrate", "uuid", "macros", "postgres", "time"] }
secrecy = { version = "0.8", features = ["serde"] }
pavex_session = "0.2.10"
pavex_session_sqlx = { version = "0.2.10", features = ["postgres"] }
uuid = { version = "1.26.1", features = ["serde", "v4"] }
thiserror = "2.0.20"
tokio = "1.53.1"
anyhow = "1.0.104"
argon2 = "0.6.0"
rand = "0.10.2"
askama = "0.16.1"
bpm-engine-bpmn = "0.2.0"
bpm-engine-core = "0.2.0"
bpm-engine-storage = "0.2.0"
async-trait = "0.1.92"
serde_json = "1.0.151"
time = { version = "0.3.55", features = ["formatting", "parsing"] }
bpm-engine-runtime = "0.2.0"
