[env]
PX_PROFILE = { value = "dev" }
PX_DATABASE__USERNAME = { value = "postgres" }
PX_DATABASE__PASSWORD = { value = "postgres" }
PX_DATABASE__PORT = { value = "5432" }
PX_DATABASE__HOST = { value = "localhost" }
PX_DATABASE__DATABASE_NAME = { value = "pavex_bpmn_process_manager_db" }
PX_DATABASE__REQUIRE_SSL = { value = "false" }
DATABASE_URL="postgres://postgres:postgres@localhost:5432/pavex_bpmn_process_manager_db"
TAILWIND_BIN_PATH = "C:\\Users\\lordb\\.cache\\tailwind-bin\\tailwindcss.exe"
