# Configuration values in this file are used by all profiles,
# unless overridden in the profile-specific configuration files
# or via an environment variable.
server:
  ip: "0.0.0.0"
  port: 8000
  graceful_shutdown_timeout: "1 minute"

cookies:
  crypto_rules:
    - cookie_names: ["id"]
      algorithm: "encryption"
      key: "7a35033bffa439f75f77e6022115f9a3b3b6efbf5c8d93998aeca36039823ab440ed55b94f6e60a622b27d12a65a530943bd8f37b31e1e29ad12ff5be3e28fb8"
      fallbacks: []